query ($name: String!, $owner: String!) {
    repository(name: $name, owner: $owner) {
        name
        owner {
            login
        }
        description
        homepageUrl
        url
        createdAt
        lastModifiedAt: pushedAt
        isArchived
        isPrivate
        visibility
        diskUsage
        licenseInfo {
            spdx: key
            name
            url
        }
        primaryLanguage {
            name
            color
        }
        languages(first: 5) {
            nodes {
                name
                color
            }
        }
        latestRelease {
            name
            tagName
            url
            description
            isDraft
            createdAt
            publishedAt
        }
        repositoryTopics(first: 5) {
            nodes {
                topic {
                    name
                }
                url
            }
        }
        collaborators {
            totalCount
        }
        stargazerCount
        forkCount
        watchers {
            totalCount
        }
    }
}
