name: Generate and Deploy API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Set up Pkl
        run: |
          curl -L -o pkl https://github.com/apple/pkl/releases/download/0.25.2/pkl-linux-amd64
          chmod +x pkl
          sudo mv pkl /usr/local/bin/pkl
          pkl --version

      - name: Setup Rust
        run: |
          rustup update stable          

      - name: Build API
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          # obtain the UID and GID of the container to avoid permission issues when creating files
          CONTAINER_UID=$(docker run --rm --entrypoint id quay.io/tama5/fauxrest:latest -u)
          CONTAINER_GID=$(docker run --rm --entrypoint id quay.io/tama5/fauxrest:latest -g)
          for i in assets/*.pkl ; do
              pkl eval -f json -o data/$(basename $i .pkl).json $i
          done
          cargo build --release
          cargo run -- --pretty --base-project-json data/base-products.json > data/products.json

          mkdir docs
          sudo chown -R $CONTAINER_UID:$CONTAINER_GID docs
          docker run -v $PWD:/opt quay.io/tama5/fauxrest:latest --dest docs data

      - name: Restore the directory permissions
        if: always()
        run:
          sudo chown -R $(id -u):$(id -g) docs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5